name: Tests

on:
  - pull_request

jobs:
  tests:
    name: ${{ matrix.session }} / py${{ matrix.python }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: "3.13", os: "ubuntu-latest",  session: "lint" }
          - { python: "3.13", os: "ubuntu-latest",  session: "mypy" }
          - { python: "3.13", os: "ubuntu-latest",  session: "tests" }
          - { python: "3.13", os: "windows-latest", session: "tests" }
          - { python: "3.13", os: "macos-latest",   session: "tests" }
          - { python: "3.13", os: "ubuntu-latest",  session: "docs-build" }

    steps:
      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v6.1.0
        with:
          python-version: ${{ matrix.python }}

      - name: Install Nox
        run: |
          python -m pip install --upgrade pip
          python -m pip install "nox>=2024.4.15"

      - name: Run Nox session
        run: |
          nox -s ${{ matrix.session }}

      - name: Upload coverage data
        if: always() && matrix.session == 'tests' && matrix.os == 'ubuntu-latest'
        uses: "actions/upload-artifact@v5.0.0"
        with:
          name: coverage-data
          path: "server/eudai/.coverage*"